status = [
  "ci/circleci: build",
  "ci/circleci: pre_test",
  "ci/circleci: test",
  "continuous-integration/appveyor/branch",
  "continuous-integration/travis-ci/push",
]
timeout_sec = 10800 # macOS on Travis CI has long waiting times
